[package]
name = "skatev-ped-export"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rage-formats = { path = "../../upstream/rage-formats", default-features = false }
serde_json = "1"
anyhow = "1"
rpf-archive = { path = "../../upstream/rpf-archive-rs" }
aes = "0.8"
lzxd = "0.2"
sha1 = "0.10"
