"""Checks that a live clip built on this machine matches the layout the ASI was
compiled with (INSTALLER-READINESS "Live clip compatibility").

live_clip writes the clip and a layout header from the player's own ped
skeletons; host/src/live_clip.cpp compiles one such header in, so a clip with a
different channel layout would drive the wrong bones. Setup activates the pack
only when this passes.

    python tools/check-clip-layout.py <generated live_clip_layout.h> [--expected host/src/live_clip_layout.h]

Exit 0: same layout. Exit 1: different (the message names the first difference).
"""
import argparse
import sys
from pathlib import Path

from _common import REPO


def layout(text):
    """The header without its provenance line (it names the clip's hash, which
    can change without the layout changing)."""
    return [l.rstrip() for l in text.splitlines() if not l.startswith('// Generated by')]


def difference(built, expected):
    """None when the layouts match, else a description of the first difference."""
    a, b = layout(built), layout(expected)
    for i, (x, y) in enumerate(zip(a, b)):
        if x != y:
            return f'line {i + 1}: {x.strip()!r} != {y.strip()!r}'
    return None if len(a) == len(b) else f'{len(a)} lines != {len(b)}'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('built', type=Path)
    ap.add_argument('--expected', type=Path, default=REPO / 'host/src/live_clip_layout.h')
    args = ap.parse_args()
    diff = difference(args.built.read_text(encoding='utf-8'), args.expected.read_text(encoding='utf-8'))
    if diff:
        print(f'live clip layout differs from the ASI\'s ({diff}); the pack must not be activated', file=sys.stderr)
        sys.exit(1)
    print('live clip layout matches the ASI')


if __name__ == '__main__':
    if len(sys.argv) > 1:
        main()
    else:  # self-check
        h = '#pragma once\n// Generated by x. sha256 aa\ninline constexpr int kChannels = 8323;\n'
        assert difference(h.replace('aa', 'bb'), h) is None
        assert 'kChannels' in difference(h.replace('8323', '8324'), h)
        assert difference(h + 'x\n', h)
        print('ok')
